name: "Convert BaekjoonHub to Jekyll Posts"

on:
  push:
    branches:
      - main
    paths:
      - "coding_test_repository/**" # 백준허브 레포지토리 내 파일이 변경될 때만 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true # 서브모듈도 함께 체크아웃

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Convert BaekjoonHub to Jekyll Posts
        run: |
          mkdir -p _posts/coding-test/baekjoon
          mkdir -p _posts/coding-test/programmers

          # 백준 문제 README.md 파일 변환
          for dir in coding_test_repository/백준/*/; do
            if [ -f "$dir/README.md" ]; then
              filename=$(basename "$dir")
              title=$(grep -m 1 '^#' "$dir/README.md" | sed 's/# //')
              date=$(date '+%Y-%m-%d')
              platform="baekjoon"

              # 언어 확인 및 코드 파일 읽기
              codefile=$(find "$dir" -type f \( -name "*.cpp" -o -name "*.py" -o -name "*.java" -o -name "*.js" \) | head -1)
              lang=$(echo "$codefile" | awk -F. '{print $NF}')
              case $lang in
                cpp) codeblock="cpp";;
                py) codeblock="python";;
                java) codeblock="java";;
                js) codeblock="javascript";;
                *) codeblock="plaintext";;
              esac

              # Jekyll 포스트 파일 생성
              echo "---" > "_posts/coding-test/$platform/$date-$filename.md"
              echo "title: \"$title\"" >> "_posts/coding-test/$platform/$date-$filename.md"
              echo "categories: [coding test, $platform]" >> "_posts/coding-test/$platform/$date-$filename.md"
              echo "tags: [coding test, $platform]" >> "_posts/coding-test/$platform/$date-$filename.md"
              echo "---" >> "_posts/coding-test/$platform/$date-$filename.md"
              cat "$dir/README.md" >> "_posts/coding-test/$platform/$date-$filename.md"

              # 코드 내용 추가
              if [ -f "$codefile" ]; then
                echo -e "\n## 정답 코드\n" >> "_posts/coding-test/$platform/$date-$filename.md"
                echo "\`\`\`$codeblock" >> "_posts/coding-test/$platform/$date-$filename.md"
                cat "$codefile" >> "_posts/coding-test/$platform/$date-$filename.md"
                echo "\`\`\`" >> "_posts/coding-test/$platform/$date-$filename.md"
              fi
            fi
          done

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add _posts/
          git commit -m "Convert BaekjoonHub files to Jekyll posts"
          git push
